# frozen_string_literal: true

require "fileutils"
require "securerandom"

module LLMProxy
  module Codex
    RUNTIME_DIR = File.expand_path("../../.llm-proxy", __dir__)
    TOKEN_FILE = File.join(RUNTIME_DIR, "bearer_token")
    AUTH_SCRIPT = File.join(RUNTIME_DIR, "auth-helper.sh")
    CODEX_CONFIG = File.expand_path("~/.codex/config.toml")
    CODEX_BACKUP = File.join(RUNTIME_DIR, "config.toml.before-llm-proxy")
    README_NOTICE = File.join(RUNTIME_DIR, "README.txt")
    MANAGED_BEGIN = "# >>> llm-proxy managed >>>"
    MANAGED_END = "# <<< llm-proxy managed <<<"

    class << self
      def enable(model_slug, config)
        port = (config.server[:port] || 8765).to_s
        proxy_name = "llm_proxy"
        config_dir = File.dirname(CODEX_CONFIG)
        Dir.mkdir(config_dir) unless Dir.exist?(config_dir)
        Dir.mkdir(RUNTIME_DIR) unless Dir.exist?(RUNTIME_DIR)

        original = File.exist?(CODEX_CONFIG) ? File.read(CODEX_CONFIG) : ""
        if !original.include?(MANAGED_BEGIN) && !File.exist?(CODEX_BACKUP)
          File.write(CODEX_BACKUP, original)
        end

        cleaned = remove_managed_sections(original)
        cleaned = remove_top_level_keys(cleaned, %w[model model_provider])
        cleaned = remove_section(cleaned, "model_providers.llm_proxy")

        token = write_token_file!
        write_auth_script!(token)

        top = <<~TOP
          #{MANAGED_BEGIN}
          model = "#{model_slug}"
          model_provider = "#{proxy_name}"
          #{MANAGED_END}
        TOP

        prov = <<~PROV
          #{MANAGED_BEGIN}
          [model_providers.#{proxy_name}]
          name = "LLM Proxy"
          base_url = "http://127.0.0.1:#{port}/v1"
          wire_api = "responses"
          request_max_retries = 3
          stream_max_retries = 3
          stream_idle_timeout_ms = 600000

          [model_providers.#{proxy_name}.auth]
          command = #{escape_path(AUTH_SCRIPT)}
          timeout_ms = 5000
          refresh_interval_ms = 300000
          #{MANAGED_END}
        PROV

        write_readme!(token)

        File.write(CODEX_CONFIG, top + "\n" + cleaned.lstrip + "\n" + prov)
        puts "✅ Proxy mode enabled — Codex will use #{model_slug} via llm-proxy"
        puts "   Restart Codex for changes to take effect."
      end

      def disable
        remove_shim_artifacts!

        unless File.exist?(CODEX_BACKUP)
          unless File.exist?(CODEX_CONFIG)
            puts "No config to restore."
            return
          end
          current = File.read(CODEX_CONFIG)
          restored = remove_managed_sections(current)
          File.write(CODEX_CONFIG, restored.lstrip)
          puts "✅ Proxy mode disabled — Codex is back to native"
          return
        end

        File.write(CODEX_CONFIG, File.read(CODEX_BACKUP))
        FileUtils.rm(CODEX_BACKUP)
        puts "✅ Proxy mode disabled — Codex restored to original config"
      end

      private

      def write_token_file!
        token = SecureRandom.hex(32)
        Dir.mkdir(RUNTIME_DIR) unless Dir.exist?(RUNTIME_DIR)
        File.write(TOKEN_FILE, token)
        File.chmod(0600, TOKEN_FILE)
        token
      end

      def write_auth_script!(token)
        Dir.mkdir(RUNTIME_DIR) unless Dir.exist?(RUNTIME_DIR)
        script = <<~SCRIPT
          #!/bin/sh
          # llm-proxy auth helper — prints bearer token for Codex.
          cat #{escape_path(TOKEN_FILE)}
        SCRIPT
        File.write(AUTH_SCRIPT, script)
        File.chmod(0700, AUTH_SCRIPT)
      end

      def write_readme!(token)
        return if File.exist?(README_NOTICE)
        notice = <<~README
          llm-proxy Codex shim directory
          ==============================
          This directory holds config artifacts generated by `llm-proxy enable`.
          It is safe to delete; re-run `llm-proxy enable codex` to regenerate.

          Generated: #{Time.now}
          Bearer token (auth-helper.sh prints this): #{token}
        README
        File.write(README_NOTICE, notice)
      end

      def remove_shim_artifacts!
        [AUTH_SCRIPT, TOKEN_FILE].each do |f|
          File.delete(f) if File.exist?(f)
        end
      end

      def escape_path(path)
        escaped = path.gsub("\\", "\\\\\\\\").gsub('"', '\\"')
        "\"#{escaped}\""
      end

      def remove_managed_sections(text)
        while text.include?(MANAGED_BEGIN)
          before, rest = text.split(MANAGED_BEGIN, 2)
          return before unless rest.include?(MANAGED_END)
          _, after = rest.split(MANAGED_END, 2)
          text = before + after
        end
        text
      end

      def remove_top_level_keys(text, keys)
        lines = text.lines
        in_top = true
        out = []
        lines.each do |line|
          in_top = false if line.strip.start_with?("[")
          key = line.split("=", 2).first&.strip
          if in_top && keys.include?(key)
          else
            out << line
          end
        end
        out.join
      end

      def remove_section(text, section)
        header = "[#{section}]"
        skip = false
        lines = text.lines
        out = []
        lines.each do |line|
          st = line.strip
          if st.start_with?("[") && st.end_with?("]")
            skip = (st == header)
            next if skip
          end
          out << line unless skip
        end
        out.join
      end
    end
  end
end
